apiVersion: v1
kind: Secret
metadata:
  name: {{ include "karpenter.fullname" . }}-alibabacloud-credentials
type: Opaque
stringData:
  config.json: |
    {
      "profiles": [
        {
          "mode": "AK",
          "access_key_id": "{{ .Values.alibabacloud.access_key_id }}",
          "access_key_secret": "{{ .Values.alibabacloud.access_key_secret }}",
          "region_id": "{{ .Values.alibabacloud.region_id }}"
        }
      ]
    }
